{
 "title": "Speedtest Monitor",
 "refresh": "5m",
 "panels": [
  {
   "title": "Ping (ms)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(ping) AS ping FROM internet_speed"
    }
   ]
  },
  {
   "title": "Download (Mbit/s)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(download) AS download FROM internet_speed"
    }
   ]
  },
  {
   "title": "Upload (Mbit/s)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(upload) AS upload FROM internet_speed"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT last(ping) AS ping FROM internet_speed WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Download / Upload",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "query": "SELECT last(download) AS \"Download\" FROM internet_speed WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "query": "SELECT last(upload) AS \"Upload\" FROM internet_speed WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}